# Generated by Django 6.0.4 on 2026-04-19 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('welfare', 'Welfare'), ('event', 'Event'), ('notice', 'Official Notice'), ('condolence', 'Condolence'), ('celebration', 'Celebration'), ('urgent', 'Urgent')], default='general', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Notice'), ('urgent', 'Urgent'), ('welfare', 'Welfare'), ('event', 'Event Communication'), ('emergency', 'Emergency'), ('condolence', 'Condolence'), ('celebration', 'Celebration')], default='general', max_length=20)),
                ('audience', models.CharField(choices=[('all', 'Everyone (Public)'), ('members', 'Registered Members Only'), ('city', 'Specific City'), ('category', 'Specific User Category')], default='all', max_length=20)),
                ('audience_filter', models.CharField(blank=True, help_text='City slug or category slug for filtered audience', max_length=100)),
                ('sender_name_override', models.CharField(blank=True, max_length=255)),
                ('sender_role_override', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='communications/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='communications/pdf/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_sent', to='leaders.leader')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='communications.communication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('communication', 'user')},
            },
        ),
    ]
