# Generated by Django 6.0.4 on 2026-04-20 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('category', models.CharField(choices=[('football', 'Football (Soccer)'), ('rugby', 'Rugby'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('athletics', 'Athletics / Track & Field'), ('marathon', 'Marathon / Running'), ('tennis', 'Tennis'), ('table_tennis', 'Table Tennis'), ('netball', 'Netball'), ('cricket', 'Cricket'), ('chess', 'Chess'), ('other', 'Other')], default='football', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='⚽', max_length=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='sports/covers/')),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('competition_type', models.CharField(choices=[('league', 'League'), ('tournament', 'Tournament / Cup'), ('friendly', 'Friendly Series'), ('championship', 'Championship')], default='tournament', max_length=20)),
                ('season', models.CharField(default='2026', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sports/competitions/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='sports.sport')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SportsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('training', 'Training Session'), ('friendly', 'Friendly Match'), ('sports_day', 'Sports Day'), ('tournament', 'Tournament'), ('meet', 'Athletics Meet'), ('social', 'Social / Awards'), ('other', 'Other')], default='training', max_length=30)),
                ('description', models.TextField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='sports/events/')),
                ('registration_open', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sports.sport')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sports/teams/')),
                ('color_primary', models.CharField(default='#00A651', max_length=20)),
                ('color_secondary', models.CharField(default='#000000', max_length=20)),
                ('founded', models.DateField(blank=True, null=True)),
                ('home_venue', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_captained', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='sports.sport')),
            ],
            options={
                'ordering': ['sport', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SportsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='sports/news/')),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sport')),
                ('related_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.team')),
            ],
            options={
                'verbose_name_plural': 'Sports news',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(choices=[('gk', 'Goalkeeper'), ('df', 'Defender'), ('mf', 'Midfielder'), ('fw', 'Forward'), ('c', 'Center'), ('g', 'Guard'), ('f', 'Forward'), ('cap', 'Captain'), ('any', 'Any / Multi-position')], default='any', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sports/players/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profiles', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sports.team')),
            ],
            options={
                'ordering': ['team', 'jersey_number', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('match_report', models.TextField(blank=True)),
                ('highlights_video_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='sports.competition')),
                ('mvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp_fixtures', to='sports.player')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='sports.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='sports.team')),
            ],
            options={
                'ordering': ['-kickoff'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='sports.team'),
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starting', models.BooleanField(default=True)),
                ('shirt_number', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(blank=True, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='sports.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='sports.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='sports.team')),
            ],
            options={
                'ordering': ['fixture', '-is_starting', 'shirt_number'],
                'unique_together': {('fixture', 'player')},
            },
        ),
    ]
