# Generated by Django 6.0.4 on 2026-04-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='embassy_cta_description',
            field=models.TextField(default='KCK helps Kenyans in Korea access embassy services through our community liaison program. Submit your request online and our officers will guide you through the process and coordinate with the Kenyan Embassy in Seoul on your behalf.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='embassy_cta_eyebrow',
            field=models.CharField(default='Embassy Liaison Service', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='embassy_cta_note',
            field=models.CharField(default='Note: Official processing and document issuance is done by the Embassy of Kenya — KCK is a community facilitator, not the embassy.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='embassy_cta_title',
            field=models.CharField(default='Need Embassy Services?', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='embassy_disclaimer_enabled',
            field=models.BooleanField(default=True, help_text='Show the embassy disclaimer banner'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='embassy_disclaimer_text',
            field=models.TextField(default='This is a community platform for Kenyans living in South Korea — not the official Kenya Embassy. For official embassy/consular services, please visit the Embassy of Kenya in Seoul.', help_text='Banner shown at top of every page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about',
            field=models.TextField(default='Supporting and connecting the Kenyan community in South Korea through embassy liaison, cultural events, and community engagement.', help_text='Description shown in footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, help_text='Custom copyright text (optional, defaults to "© YEAR SITE_NAME. All rights reserved.")', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge_text',
            field=models.CharField(default='Kenyan Community · Seoul · Korea', help_text='Small pill text above hero title', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_primary_text',
            field=models.CharField(default='Join the Community', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_secondary_text',
            field=models.CharField(default='Upcoming Events', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_accent',
            field=models.CharField(default='in Korea', help_text='Part of hero title shown in gold', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional custom logo (otherwise uses default KCK logo)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_description',
            field=models.CharField(default='Get updates on community news, events, and announcements.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_title',
            field=models.CharField(default='Subscribe to Newsletter', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_short_name',
            field=models.CharField(default='KCK', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slogan',
            field=models.CharField(default='SOTE PAMOJA', help_text='Community slogan (displayed site-wide)', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slogan_description',
            field=models.CharField(default='the spirit of our community', help_text='Short descriptor shown under slogan', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slogan_translation',
            field=models.CharField(default='All Together', help_text='English translation of the slogan', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='A community platform connecting, supporting and celebrating Kenyans across South Korea — events, embassy liaison, official communications, and a space that feels like home.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Kenya Community', max_length=255),
        ),
    ]
