# Generated by Django 6.0.4 on 2026-04-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_embassy_cta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='discover_cuisine_text',
            field=models.TextField(default="Kenyan cuisine is as diverse as its people. Savour nyama choma (grilled meat), ugali (cornmeal staple), sukuma wiki (collard greens), pilau rice, chapati, and coastal seafood dishes infused with Swahili spices.\n\nDon't miss a cup of Kenyan coffee or tea — globally celebrated for their rich flavour and quality."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='discover_cuisine_title',
            field=models.CharField(default='Food & Cuisine', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='discover_culture_text',
            field=models.TextField(default="Kenya's cultural diversity is one of its greatest treasures. The country is home to communities such as the Kikuyu, Luo, Kalenjin, Maasai, Kamba, Luhya, and many more, each with unique traditions, music, dance, and cuisine.\n\nExplore traditional crafts, attend cultural festivals, and experience the warm hospitality Kenya is known for."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='discover_culture_title',
            field=models.CharField(default='Culture & Heritage', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='discover_hero_image',
            field=models.ImageField(blank=True, help_text='Optional hero background image for /discover/', null=True, upload_to='discover/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='discover_hero_subtitle',
            field=models.CharField(default='The Magic of Kenya — a land of stunning landscapes, vibrant cultures, and unforgettable experiences.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='discover_hero_title',
            field=models.CharField(default='Discover Kenya', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='discover_intro_image',
            field=models.ImageField(blank=True, help_text='Image shown next to the "Karibu Kenya" intro text', null=True, upload_to='discover/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='discover_intro_text',
            field=models.TextField(default='Kenya is a country of breathtaking beauty and remarkable diversity. From the iconic savannahs of the Maasai Mara to the snow-capped peak of Mount Kenya, from the pristine beaches of the Indian Ocean to the bustling streets of Nairobi, Kenya offers an experience like no other.\n\nHome to over 50 million people and 44 ethnic communities, Kenya is a mosaic of cultures, languages, and traditions. Swahili and English are the official languages.\n\nWhether you are seeking adventure, culture, relaxation, or business opportunities, Kenya welcomes you with open arms and unforgettable memories.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='discover_intro_title',
            field=models.CharField(default='Karibu Kenya', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='info@kenyakorea.com', max_length=254),
        ),
    ]
