# Generated by Django 6.0.4 on 2026-04-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_discover_cuisine_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='embassy_official_name',
            field=models.CharField(default='Embassy of the Republic of Kenya, Seoul', help_text='Display name of the official embassy', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='embassy_official_url',
            field=models.URLField(default='https://kenya-embassy.or.kr', help_text='Official website of the Embassy of Kenya in Seoul'),
        ),
    ]
