# Generated by Django 6.0.4 on 2026-04-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_embassy_official_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_swift',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_page_intro',
            field=models.TextField(default='Become a member of the Kenya Community in Korea. One annual fee unlocks the full benefits of belonging.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_page_title',
            field=models.CharField(default='KCK Membership', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='treasurer_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='treasurer_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
