# Generated by Django 6.0.4 on 2026-04-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members_only',
            field=models.BooleanField(default=False, help_text='If on, only paid-up KCK members can register for this event.'),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_enabled',
            field=models.BooleanField(default=True, help_text='If on, users who register after capacity is reached are added to a waitlist and promoted automatically when seats open up.'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='is_member',
            field=models.BooleanField(default=False, help_text='Snapshot of membership status at registration time (used for waitlist priority).'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='promoted_at',
            field=models.DateTimeField(blank=True, help_text='When (if) this registration was promoted from waitlist to confirmed.', null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='promotion_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='waitlist_position',
            field=models.PositiveIntegerField(blank=True, help_text='Position in the waitlist queue (1 = next in line). Null when registered.', null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('waitlisted', 'On Waitlist'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='registered', max_length=20),
        ),
    ]
