# Generated by Django 6.0.4 on 2026-04-20 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('icon', models.CharField(blank=True, default='🛍️', help_text='Emoji or Bootstrap icon class', max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Product categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='Main product photo', upload_to='market/products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('KRW', '₩ KRW (Korean Won)'), ('USD', '$ USD'), ('KES', 'KSh KES (Kenyan Shilling)')], default='KRW', max_length=3)),
                ('free_delivery_korea', models.BooleanField(default=False, help_text='Free delivery anywhere in Korea')),
                ('delivery_option', models.CharField(choices=[('free_korea', 'Free delivery anywhere in Korea'), ('free_city', 'Free delivery within my city'), ('paid', 'Delivery available (buyer pays)'), ('pickup_only', 'Pickup only — no delivery'), ('meetup', 'Meet-up arranged via WhatsApp')], default='meetup', max_length=20)),
                ('delivery_notes', models.CharField(blank=True, help_text='Details about delivery, pickup points, fees (if any)', max_length=500)),
                ('city', models.CharField(choices=[('seoul', 'Seoul'), ('busan', 'Busan'), ('incheon', 'Incheon'), ('daegu', 'Daegu'), ('daejeon', 'Daejeon'), ('gwangju', 'Gwangju'), ('ulsan', 'Ulsan'), ('other', 'Other')], default='seoul', help_text='Where the product is located', max_length=20)),
                ('whatsapp_link_override', models.URLField(blank=True, help_text='Optional: custom WhatsApp link for this product (defaults to your seller WhatsApp)')),
                ('whatsapp_message_template', models.CharField(blank=True, help_text='Pre-filled message, e.g. "Hi! I\'m interested in {product_name}"', max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='market.productcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='market/products/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='market.product')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('bio', models.TextField(help_text='Tell buyers about your business and what you sell')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='market/sellers/')),
                ('whatsapp_number', models.CharField(help_text='International format preferred: +82 10 1234 5678 or +254 7xx xxx xxx', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, help_text='e.g. Seoul, Busan, Incheon', max_length=50)),
                ('location_notes', models.CharField(blank=True, help_text='e.g. "Near Itaewon Station" — helps buyers plan pickups', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Internal notes or rejection reason')),
                ('active', models.BooleanField(default=True, help_text='Uncheck to temporarily hide this seller')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_applications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.sellerprofile'),
        ),
    ]
