# Generated by Django 6.0.4 on 2026-04-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_description', models.TextField(help_text='Shown on the card (keep under 250 chars).')),
                ('description', models.TextField(blank=True, help_text='Longer description (optional).')),
                ('image', models.ImageField(blank=True, help_text='Ideal size: 800x600px', null=True, upload_to='discover/attractions/')),
                ('icon', models.CharField(blank=True, default='bi-geo-alt', help_text='Bootstrap Icon class (e.g. "bi-tree") or emoji', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TravelEssential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(help_text='e.g. "Kenyan Shilling (KES)"', max_length=255)),
                ('icon', models.CharField(blank=True, default='bi-info-circle', help_text='Bootstrap Icon class (e.g. "bi-currency-exchange")', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
