# Generated by Django 6.0.4 on 2026-04-19 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_name', models.CharField(help_text='Full name as it should appear on certificate', max_length=255)),
                ('cert_type', models.CharField(choices=[('appreciation', 'Certificate of Appreciation'), ('participation', 'Certificate of Participation'), ('leadership', 'Leadership Certificate'), ('welfare', 'Welfare Certificate'), ('membership', 'Membership Certificate'), ('recognition', 'Certificate of Recognition'), ('custom', 'Custom Certificate')], default='appreciation', max_length=30)),
                ('title', models.CharField(blank=True, help_text='Custom title (for custom type)', max_length=255)),
                ('body', models.TextField(help_text='Body text shown on certificate')),
                ('event_title', models.CharField(blank=True, help_text='Related event/occasion (optional)', max_length=255)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('issued_by_name', models.CharField(blank=True, help_text='Name override if no leader selected', max_length=255)),
                ('issued_by_role', models.CharField(blank=True, help_text='Role override if no leader selected', max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdf/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('published', 'Published'), ('revoked', 'Revoked'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('revoke_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_created', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to='leaders.leader')),
                ('recipient_user', models.ForeignKey(blank=True, help_text='Leave blank if recipient is not a registered user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
