# Generated by Django 6.0.4 on 2026-04-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_korea',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('worker', 'Worker'), ('professional', 'Professional'), ('tourist', 'Tourist'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('seoul', 'Seoul'), ('busan', 'Busan'), ('incheon', 'Incheon'), ('daegu', 'Daegu'), ('daejeon', 'Daejeon'), ('gwangju', 'Gwangju'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='korean_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
