# Generated by Django 6.0.4 on 2026-04-21 11:06

import django.db.models.deletion
import memberships.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-check-circle-fill', help_text='Bootstrap Icon class, e.g. bi-shield-fill', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Membership Benefit',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='KCK Individual Member', max_length=100)),
                ('annual_amount', models.DecimalField(decimal_places=0, default=50000, help_text='Annual fee in the currency below.', max_digits=10)),
                ('currency', models.CharField(default='KRW', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Short description shown on the membership page.')),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Tier',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(blank=True, help_text='Assigned on first activation. Persistent across renewals.', max_length=30, null=True, unique=True)),
                ('reference_code', models.CharField(default=memberships.models._gen_reference_code, help_text='Unique code the member uses in their bank transfer description.', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('awaiting_verification', 'Awaiting Verification'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending_payment', max_length=30)),
                ('expected_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('currency', models.CharField(default='KRW', max_length=10)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_declared_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reminder_30_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_7_sent_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_notified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_memberships', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.membershiptier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('apply', 'Member applied'), ('declare_payment', 'Member declared payment'), ('verify', 'Treasurer verified payment'), ('reject', 'Treasurer rejected payment'), ('expire', 'Membership expired'), ('renew', 'Member renewed'), ('tier_edit', 'Tier edited'), ('bank_edit', 'Bank details edited'), ('benefit_edit', 'Benefits edited'), ('reminder_sent', 'Expiry reminder sent'), ('member_number_assigned', 'Member number assigned')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form JSON for extra context (e.g. old/new values).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='memberships.membership')),
            ],
            options={
                'verbose_name': 'Membership Audit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('claimed_date', models.DateField(help_text='Date the user says they sent the transfer.')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='memberships/proof/')),
                ('notes', models.TextField(blank=True, help_text='Any note from the user about the transfer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='memberships.membership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
