# Generated by Django 6.0.4 on 2026-04-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_number',
            field=models.CharField(blank=True, db_index=True, help_text='Assigned on first activation. Persistent across renewals — the same number is reused for every subsequent membership row of the same user.', max_length=30, null=True),
        ),
    ]
