# Generated by Django 6.0.4 on 2026-04-19 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embassy_liaison', '0001_initial'),
        ('leaders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('member_full_name', models.CharField(help_text='Full name as it should appear on the letter', max_length=255)),
                ('member_id_number', models.CharField(blank=True, help_text='Kenyan National ID / Passport number', max_length=100)),
                ('endorsement_type', models.CharField(choices=[('cover_note', 'Cover Note'), ('endorsement', 'Letter of Endorsement'), ('introduction', 'Letter of Introduction'), ('recommendation', 'Letter of Recommendation'), ('verification', 'Membership Verification Letter'), ('to_whom', 'To Whom It May Concern')], default='cover_note', max_length=30)),
                ('subject', models.CharField(help_text='e.g. "Cover Note for Passport Renewal Application"', max_length=255)),
                ('addressed_to', models.CharField(blank=True, help_text='e.g. "The Ambassador, Kenyan Embassy in Seoul" — leave blank for "To Whom It May Concern"', max_length=255)),
                ('addressed_to_address', models.TextField(blank=True, help_text='Recipient address (optional)')),
                ('purpose', models.CharField(help_text='Brief statement of purpose', max_length=500)),
                ('body', models.TextField(help_text='Main body of the endorsement letter')),
                ('member_standing', models.TextField(blank=True, help_text='Description of member standing (e.g. "A registered active member since 2023")')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Leave blank if endorsement does not expire', null=True)),
                ('issued_by_name', models.CharField(blank=True, max_length=255)),
                ('issued_by_role', models.CharField(blank=True, max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='endorsements/pdf/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating PDF'), ('issued', 'Issued'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('revoke_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsements_created', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsements_issued', to='leaders.leader')),
                ('related_service_request', models.ForeignKey(blank=True, help_text='Link to an existing embassy service request (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsements', to='embassy_liaison.embassyservicerequest')),
                ('user', models.ForeignKey(blank=True, help_text='The KCK member being endorsed (leave blank if non-member)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsements_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
