# Generated by Django 6.0.4 on 2026-04-19 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chairman', 'Chairman'), ('vice_chairman', 'Vice Chairman'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('welfare', 'Welfare Officer'), ('committee', 'Committee Member')], max_length=30)),
                ('title', models.CharField(blank=True, help_text='Display title, e.g. "Chairman of KCK"', max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leaders/')),
                ('signature', models.ImageField(blank=True, help_text='Signature image for documents', null=True, upload_to='leaders/signatures/')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='leaders/stamps/')),
                ('email_official', models.EmailField(blank=True, max_length=254)),
                ('phone_official', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('appointed_at', models.DateField(blank=True, null=True)),
                ('term_ends', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'role'],
            },
        ),
        migrations.CreateModel(
            name='LeaderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_verify_users', models.BooleanField(default=False)),
                ('can_export_users', models.BooleanField(default=False)),
                ('can_manage_memberships', models.BooleanField(default=False)),
                ('can_view_financials', models.BooleanField(default=False)),
                ('can_send_communications', models.BooleanField(default=False)),
                ('can_issue_certificates', models.BooleanField(default=False)),
                ('can_manage_events', models.BooleanField(default=False)),
                ('can_manage_leaders', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='leaders.leader')),
            ],
        ),
    ]
