# Generated by Django 6.0.4 on 2026-04-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('welfare', 'Welfare Officer'), ('committee', 'Committee Member')], max_length=30),
        ),
        migrations.AlterField(
            model_name='leader',
            name='title',
            field=models.CharField(blank=True, help_text='Display title, e.g. "President of KCK"', max_length=255),
        ),
    ]
