# Generated by Django 6.0.4 on 2026-04-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0003_rename_chairman_to_president'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='message',
            field=models.TextField(blank=True, help_text="Official public message / statement from this leader (e.g. the President's Message shown on the homepage)."),
        ),
        migrations.AddField(
            model_name='leader',
            name='message_title',
            field=models.CharField(blank=True, help_text='Heading for the message, e.g. "A Message from Our President".', max_length=200),
        ),
        migrations.AddField(
            model_name='leader',
            name='show_message_on_home',
            field=models.BooleanField(default=False, help_text="Feature this leader's message on the homepage."),
        ),
    ]
