# Generated by Django 6.0.4 on 2026-04-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0004_leader_message_leader_message_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderpermission',
            name='can_manage_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaderpermission',
            name='can_manage_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaderpermission',
            name='can_review_embassy_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaderpermission',
            name='can_review_endorsements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaderpermission',
            name='can_review_market_sellers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaderpermission',
            name='can_view_audit_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaderpermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
