# Generated by Django 6.0.4 on 2026-04-24 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0005_leaderpermission_can_manage_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(blank=True, help_text='The permission flag that was changed; blank if "all" / role default reset.', max_length=60)),
                ('old_value', models.BooleanField(blank=True, null=True)),
                ('new_value', models.BooleanField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, help_text='Human description e.g. "Reset to role defaults" or "Granted can_view_audit_log".', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_logs', to='leaders.leader')),
            ],
            options={
                'verbose_name': 'Permission Audit Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
