# Generated by Django 6.0.4 on 2026-04-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0006_permissionauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary General'), ('treasurer', 'Treasurer'), ('welfare', 'Welfare Officer'), ('committee', 'Committee Member')], max_length=30),
        ),
    ]
