# Generated by Django 6.0.4 on 2026-04-19 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('passport_new', 'New Passport Application'), ('passport_renewal', 'Passport Renewal'), ('passport_replacement', 'Passport Replacement (Lost/Damaged)'), ('emergency_travel', 'Emergency Travel Document (ETD)'), ('national_id', 'National ID Application/Renewal'), ('birth_certificate', 'Birth Certificate Application'), ('notarization', 'Document Notarization / Authentication'), ('citizen_registration', 'Citizen Registration (Diaspora)'), ('consular_letter', 'Consular Letter Request'), ('visa_kenya', 'Kenya Visa Information / Guidance'), ('appointment_booking', 'Embassy Appointment Booking Assistance'), ('other', 'Other Embassy Service')], max_length=40, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(default=list, help_text='List of required documents/information')),
                ('typical_timeline', models.CharField(blank=True, help_text='e.g. "2-4 weeks"', max_length=100)),
                ('embassy_fee', models.CharField(blank=True, help_text='Fees charged by Embassy', max_length=100)),
                ('kck_facilitation_fee', models.CharField(default='Free', help_text='Fees charged by KCK (if any)', max_length=100)),
                ('icon', models.CharField(blank=True, default='📋', max_length=10)),
                ('additional_info', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EmbassyServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('service_type', models.CharField(choices=[('passport_new', 'New Passport Application'), ('passport_renewal', 'Passport Renewal'), ('passport_replacement', 'Passport Replacement (Lost/Damaged)'), ('emergency_travel', 'Emergency Travel Document (ETD)'), ('national_id', 'National ID Application/Renewal'), ('birth_certificate', 'Birth Certificate Application'), ('notarization', 'Document Notarization / Authentication'), ('citizen_registration', 'Citizen Registration (Diaspora)'), ('consular_letter', 'Consular Letter Request'), ('visa_kenya', 'Kenya Visa Information / Guidance'), ('appointment_booking', 'Embassy Appointment Booking Assistance'), ('other', 'Other Embassy Service')], max_length=40)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under KCK Review'), ('additional_info', 'Additional Information Needed'), ('forwarded', 'Forwarded to Embassy'), ('embassy_processing', 'Being Processed by Embassy'), ('appointment_scheduled', 'Embassy Appointment Scheduled'), ('ready_for_pickup', 'Ready for Collection'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by Member')], default='submitted', max_length=30)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('full_name', models.CharField(help_text='As on Kenyan ID/Passport', max_length=255)),
                ('kenyan_id_number', models.CharField(blank=True, help_text='National ID number', max_length=50)),
                ('current_document_number', models.CharField(blank=True, help_text='Current passport/ID number if renewing or replacing', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('korean_phone', models.CharField(blank=True, max_length=20)),
                ('address_in_korea', models.TextField()),
                ('city', models.CharField(blank=True, max_length=50)),
                ('purpose', models.TextField(help_text='Why you need this service')),
                ('urgency_reason', models.TextField(blank=True, help_text='If urgent/emergency, explain why')),
                ('preferred_appointment_date', models.DateField(blank=True, null=True)),
                ('supporting_document_1', models.FileField(blank=True, null=True, upload_to='embassy_requests/')),
                ('supporting_document_2', models.FileField(blank=True, null=True, upload_to='embassy_requests/')),
                ('supporting_document_3', models.FileField(blank=True, null=True, upload_to='embassy_requests/')),
                ('consent_data_sharing', models.BooleanField(default=False, help_text='I consent to KCK forwarding my data to the Kenyan Embassy')),
                ('consent_privacy_policy', models.BooleanField(default=False, help_text='I have read and agree to the KCK privacy policy')),
                ('embassy_reference', models.CharField(blank=True, help_text='Embassy reference number once forwarded', max_length=100)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal KCK notes (not visible to member)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_officer', models.ForeignKey(blank=True, help_text='KCK officer handling this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_embassy_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embassy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('member_message', 'Message from Member'), ('officer_reply', 'Reply from KCK Officer'), ('status_change', 'Status Change'), ('system', 'System Update')], default='member_message', max_length=20)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='embassy_requests/notes/')),
                ('is_internal', models.BooleanField(default=False, help_text='If true, only visible to KCK officers (not the member)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='embassy_liaison.embassyservicerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
